version: '3.8'

services:
    mongodb:
        container_name: ktq-news-db
        image: mongo:latest
        ports:
            - '27017:27017'
        volumes:
            - ./data/db:/data/db
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: 123
        restart: always
